### ISSUE TITLE
Halo skins?

### ISSUE THREAD

**Issue by kylepitcock** [Pigzone00/Legacy-Skin-Packs#4]
I saw on the modrinth page that unlike the others with an X under planned, it is not linked.  is there a reason for this.  the super mario mash up pack also leads to a dead link.

**Comment by FR00TP3NCH** [comment]
people are making a port of the mashup packs with the skins so we don't gotta add them

**Comment by Pigzone00** [comment]
Updated Super mario mash up link

**Comment by Pigzone00** [comment]
Updated Super mario mash up link
